// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3heqEo42vDwSVwExrLJmZwkWc7OAwii0',
    appId: '1:912877716404:web:3f24ad80ddcddbd40ba8e1',
    messagingSenderId: '912877716404',
    projectId: 'calendar-scheduler-cee11',
    authDomain: 'calendar-scheduler-cee11.firebaseapp.com',
    storageBucket: 'calendar-scheduler-cee11.appspot.com',
    measurementId: 'G-TCCSSP4LG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0zAE0jGtYOXtosKvFOY60a1XVPh7xz0A',
    appId: '1:912877716404:android:5e3624fe329f86b50ba8e1',
    messagingSenderId: '912877716404',
    projectId: 'calendar-scheduler-cee11',
    storageBucket: 'calendar-scheduler-cee11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrFmsDYYo-SCvAdbNBaAeK2SrQuOKecFw',
    appId: '1:912877716404:ios:2e43123bb45d46e10ba8e1',
    messagingSenderId: '912877716404',
    projectId: 'calendar-scheduler-cee11',
    storageBucket: 'calendar-scheduler-cee11.appspot.com',
    iosBundleId: 'com.example.ch17CalendarSchedulerDesktop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrFmsDYYo-SCvAdbNBaAeK2SrQuOKecFw',
    appId: '1:912877716404:ios:2e43123bb45d46e10ba8e1',
    messagingSenderId: '912877716404',
    projectId: 'calendar-scheduler-cee11',
    storageBucket: 'calendar-scheduler-cee11.appspot.com',
    iosBundleId: 'com.example.ch17CalendarSchedulerDesktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3heqEo42vDwSVwExrLJmZwkWc7OAwii0',
    appId: '1:912877716404:web:13a191670095f5c60ba8e1',
    messagingSenderId: '912877716404',
    projectId: 'calendar-scheduler-cee11',
    authDomain: 'calendar-scheduler-cee11.firebaseapp.com',
    storageBucket: 'calendar-scheduler-cee11.appspot.com',
    measurementId: 'G-7YKZ10TEN1',
  );
}